local setup, transparent = pcall(require, "transparent")
if not setup then
	return
end

transparent.setup({
	groups = { -- table: default groups
		"Normal",
		"NormalNC",
		"Comment",
		"Constant",
		"Special",
		"Identifier",
		"Statement",
		"PreProc",
		"Type",
		"Underlined",
		"Todo",
		"String",
		"Function",
		"Conditional",
		"Repeat",
		"Operator",
		"Structure",
		"LineNr",
		"NonText",
		"SignColumn",
		"CursorLine",
		"CursorLineNr",
		"StatusLine",
		"StatusLineNC",
		"EndOfBuffer",
		"TabLine",
		"TabLineFill",
		"TabLineSel",
		"WinBar",
		"WinBarNC",
		"VertSplit",
		"WinSeparator",
		"Folded",
		"FoldColumn",
		"CursorColumn",
		"LualineNormal",
		"LualineInsert",
		"LualineVisual",
		"LualineReplace",
		"LualineCommand",
		"LualineInactive",
	},
	extra_groups = { -- table: additional groups that should be cleared
		"NvimTree",
		"NvimTreeNormal",
		"NvimTreeVertSplit",
		"NvimTreeStatusLine",
		"NvimTreeStatusLineNC",
		"LuaLine",
	},
	exclude_groups = {}, -- table: groups you don't want to clear
})
